#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/raimondeaug/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
nitrogen --set-scaled
/home/raimondeaug/.fluxbox/backgrounds/PANO_20150728_181517.jpg
#nitrogen --restore &
conky & > /dev/null 2>&1 
/usr/bin/xscreensaver -no-splash &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/raimondeaug/.fluxbox/log"
